imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    #esi: 
    http_method_override: true            ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        ['SiteBundle','FOSUserBundle',"FOSCommentBundle",'AppBundle']
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
#        less:
#            node: /usr/local/bin/node
#            node_paths: [/usr/local/lib/node_modules]
#            apply_to: "\.less$"
#    assets:
#        bootstrap_css:
#            inputs:
#                - %kernel.root_dir%/../vendor/twbs/bootstrap/less/bootstrap.less
#                - %kernel.root_dir%/../vendor/braincrafted/bootstrap-bundle/Braincrafted/Bundle/BootstrapBundle/Resources/less/form.less
#            filters:
#                - less
#                - cssrewrite
#            output: css/bootstrap.css
#        bootstrap_js:
#            inputs:
#                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/transition.js
#                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/alert.js
#                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/button.js
#                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/carousel.js
#                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/collapse.js
#                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/dropdown.js
#                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/modal.js
#                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/tooltip.js
#                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/popover.js
#                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/scrollspy.js
#                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/tab.js
#                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/affix.js
#                - %kernel.root_dir%/../vendor/braincrafted/bootstrap-bundle/Braincrafted/Bundle/BootstrapBundle/Resources/js/bc-bootstrap-collection.js
#            output: js/bootstrap.js
#        jquery:
#            inputs:
#                - %kernel.root_dir%/../vendor/jquery/jquery/jquery-1.11.1.js
#            output: js/jquery.js   
#        braincrafted_bootstrap:
#            auto_configure:
#                knp_menu: false
#
#        knp_menu:
#            twig:
#                template: BraincraftedBootstrapBundle:Menu:bootstrap.html.twig    
# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

#fosuser
# app/config/config.yml
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: register
    user_class: AppBundle\Entity\User
    profile:
        form:
            type: appbundle_user
            handler : appbundle_user.form.handler.profile
    registration:
        confirmation:
            enabled : true
    from_email:
        address:        jeanraynal.bebel@gmail.com
        sender_name:    webmaster       
#fosrestBundle
fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener: true
    allowed_methods_listener: true
    serializer:
        serialize_null: true
    view:
      
        formats:
            json : true
        templating_formats:
            xml:  false
            json: true
            rss:  false
            yml:  true
           
        force_redirects:
            json: true
        failed_validation: HTTP_BAD_REQUEST
     #   default_engine: twig
    routing_loader:
        default_format: json
    format_listener: true
      # rules:
            # setting fallback_format to json means that instead of considering the next rule in case of a priority mismatch, json will be used
        #    - { path: '^/', host: 'api.%domain%', priorities: ['json'], fallback_format: json, prefer_extension: true }

#foscomment
fos_comment:
    db_driver: orm
    class:
        model:
            comment: CommentBundle\Entity\Comment
            thread: CommentBundle\Entity\Thread


jms_serializer:
    metadata:
        directories:
            FOSUB:
                namespace_prefix: "FOS\\UserBundle"
                path: "%kernel.root_dir%/serializer/FOSUserBundle"

    #LexikJWTAuthenticationBundle

lexik_jwt_authentication:
    private_key_path:    %kernel.root_dir%/var/jwt/private.pem   # ssh private key path
    public_key_path:     %kernel.root_dir%/var/jwt/public.pem    # ssh public key path
    pass_phrase:         'boulangerie'                           # ssh key pass phrase
    token_ttl:           86400                                   # token ttl - defaults to 86400
    encoder_service:     lexik_jwt_authentication.jwt_encoder    # token encoder / decoder service - defaults to the jwt encoder (based on the namshi/jose library)


nelmio_cors:
   defaults:
       allow_credentials: true
       allow_origin: []
       allow_headers: []
       allow_methods: []
       expose_headers: []
       max_age: 0
       hosts: []
   paths:
    '^/api/':
        allow_origin: ['*']
        allow_headers: "*"
        allow_methods: ['POST', 'PUT', 'GET', 'DELETE','OPTIONS']
        max_age: 3600
    '^/api/login':
        allow_origin: ['*']
        allow_headers: ['X-Custom-Auth']
        allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
        max_age: 3600