security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    firewalls:


        api_login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            form_login:
                provider: fos_userbundle
                check_path: /api/login_check
                username_parameter: username
                password_parameter: password
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false
               

        api:
            pattern:   ^/api/
            provider: fos_userbundle
            anonymous: true
            stateless: true
            
            lexik_jwt: 
                
                authorization_header:
                   enabled: true
                   prefix: Bearer
                query_parameter:
                   enabled: true
                   name: bearer
                
        main:
            pattern: ^/            
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                default_target_path:            /Film/Film
            logout:       true
            anonymous:    true   
    role_hierarchy:
        ROLE_USER : ROLE_USER
    access_control:
        - { path: ^/Film,role: ROLE_USER }
        - { path: ^/home,role: ROLE_USER }
        - { path: ^/Amis,role: ROLE_USER }
        #- { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }