<?php

namespace FilmBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MoviesfavoriteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoviesfavoriteRepository extends EntityRepository {

    public function FindMymovies($id) {

        $maxResults = 4;
        $qb = $this->createQueryBuilder('a');
        $sort = 'a.dateVu';
        $tri = 'DESC';
        $qb
                ->where('a.iduser = :id')
                ->setParameter('id', $id)
                ->setMaxResults($maxResults)
                ->orderBy($sort, $tri);

        return $qb
                        ->getQuery()
                        ->getResult()
        ;
    }

    public function FindAllmovies($id) {


        $qb = $this->createQueryBuilder('a');
        $sort = 'a.dateVu';
        $tri = 'DESC';
        $qb
                ->where('a.iduser = :id')
                ->setParameter('id', $id)
                ->orderBy($sort, $tri);
        ;

        return $qb
                        ->getQuery()
                        ->getResult()
        ;
    }

}
